#include <common.h>

typedef struct WmCullInfo {
    float distance; // no idea what this is relative to
    const char *nodeName;
} WmCullInfo;

// the dummy data that nintendo uses for unused entries
#define WM_EMPTY_CULL {100.0f, ""}

// Supports up to 30 bones per world
WmCullInfo wmNodeCullTable[9][30] = {
    { // WORLD 1
        WM_EMPTY_CULL,
        WM_EMPTY_CULL,
        WM_EMPTY_CULL,
        WM_EMPTY_CULL,
        WM_EMPTY_CULL,
        WM_EMPTY_CULL,
        WM_EMPTY_CULL,
        WM_EMPTY_CULL,
        WM_EMPTY_CULL,
        WM_EMPTY_CULL,
        WM_EMPTY_CULL,
        WM_EMPTY_CULL,
        WM_EMPTY_CULL,
        WM_EMPTY_CULL,
        WM_EMPTY_CULL,
        WM_EMPTY_CULL,
        WM_EMPTY_CULL,
        WM_EMPTY_CULL,
        WM_EMPTY_CULL,
        WM_EMPTY_CULL,
        WM_EMPTY_CULL,
        WM_EMPTY_CULL,
        WM_EMPTY_CULL,
        WM_EMPTY_CULL,
        WM_EMPTY_CULL,
        WM_EMPTY_CULL,
        WM_EMPTY_CULL,
        WM_EMPTY_CULL,
        WM_EMPTY_CULL,
        WM_EMPTY_CULL,
    },

    { // WORLD 2
        {150.0f, "desert01"},
        {100.0f, "desert02"},
        {100.0f, "desert03"},
        {150.0f, "desert04"},
        {100.0f, "desert05"},
        {100.0f, "desert06"},
        {130.0f, "desert07"},
        {100.0f, "desert08"},
        {100.0f, "desert09"},
        {100.0f, "desert10"},
        {100.0f, "desert11"},
        {300.0f, "Pyramid"},
        {900.0f, "sandtide"},
        {350.0f, "island01"},
        {130.0f, "island02"},
        {120.0f, "island03"},
        {700.0f, "island04"},
        {500.0f, "backGround"},
        WM_EMPTY_CULL,
        WM_EMPTY_CULL,
        WM_EMPTY_CULL,
        WM_EMPTY_CULL,
        WM_EMPTY_CULL,
        WM_EMPTY_CULL,
        WM_EMPTY_CULL,
        WM_EMPTY_CULL,
        WM_EMPTY_CULL,
        WM_EMPTY_CULL,
        WM_EMPTY_CULL,
        WM_EMPTY_CULL,
    },

    { // WORLD 3
        {300.0f, "snow00"},
        {300.0f, "snow01"},
        {300.0f, "snow02"},
        {300.0f, "snow03"},
        {300.0f, "snow04"},
        {300.0f, "snow05"},
        {300.0f, "snow06"},
        {300.0f, "snow07"},
        {300.0f, "snow08"},
        {300.0f, "snow09"},
        WM_EMPTY_CULL,
        WM_EMPTY_CULL,
        WM_EMPTY_CULL,
        WM_EMPTY_CULL,
        WM_EMPTY_CULL,
        WM_EMPTY_CULL,
        WM_EMPTY_CULL,
        WM_EMPTY_CULL,
        WM_EMPTY_CULL,
        WM_EMPTY_CULL,
        WM_EMPTY_CULL,
        WM_EMPTY_CULL,
        WM_EMPTY_CULL,
        WM_EMPTY_CULL,
        WM_EMPTY_CULL,
        WM_EMPTY_CULL,
        WM_EMPTY_CULL,
        WM_EMPTY_CULL,
        WM_EMPTY_CULL,
        WM_EMPTY_CULL,
    },

    { // WORLD 4
        {300.0f, "group01"},
        {250.0f, "group02"},
        {250.0f, "group03"},
        {200.0f, "group04"},
        {350.0f, "group05"},
        {250.0f, "group06"},
        {200.0f, "group07"},
        {200.0f, "group08"},
        {200.0f, "group09"},
        {400.0f, "group10"},
        {450.0f, "group11"},
        {500.0f, "group12"},
        {450.0f, "group13"},
        {800.0f, "group14"},
        {550.0f, "group15"},
        {250.0f, "group16"},
        {250.0f, "group17"},
        {200.0f, "group18"},
        {300.0f, "group19"},
        WM_EMPTY_CULL,
        WM_EMPTY_CULL,
        WM_EMPTY_CULL,
        WM_EMPTY_CULL,
        WM_EMPTY_CULL,
        WM_EMPTY_CULL,
        WM_EMPTY_CULL,
        WM_EMPTY_CULL,
        WM_EMPTY_CULL,
        WM_EMPTY_CULL,
        WM_EMPTY_CULL,
    },

    { // WORLD 5
        {400.0f, "group00"},
        {350.0f, "group01"},
        {400.0f, "group02"},
        {400.0f, "group03"},
        {400.0f, "group04"},
        {350.0f, "group05"},
        {350.0f, "group06"},
        {350.0f, "group07"},
        {350.0f, "group08"},
        {400.0f, "group04_2"},
        WM_EMPTY_CULL,
        WM_EMPTY_CULL,
        WM_EMPTY_CULL,
        WM_EMPTY_CULL,
        WM_EMPTY_CULL,
        WM_EMPTY_CULL,
        WM_EMPTY_CULL,
        WM_EMPTY_CULL,
        WM_EMPTY_CULL,
        WM_EMPTY_CULL,
        WM_EMPTY_CULL,
        WM_EMPTY_CULL,
        WM_EMPTY_CULL,
        WM_EMPTY_CULL,
        WM_EMPTY_CULL,
        WM_EMPTY_CULL,
        WM_EMPTY_CULL,
        WM_EMPTY_CULL,
        WM_EMPTY_CULL,
        WM_EMPTY_CULL,
    },

    { // WORLD 6
        {400.0f, "RockA1"},
        {300.0f, "RockA2"},
        {250.0f, "RockB1"},
        {300.0f, "RockB2"},
        {400.0f, "RockB3"},
        {200.0f, "RockB4"},
        {400.0f, "RockC1"},
        {450.0f, "RockC2"},
        {300.0f, "RockC3"},
        {350.0f, "RockD1"},
        {400.0f, "RockD2"},
        {350.0f, "RockD3"},
        {300.0f, "RockD4"},
        {200.0f, "RockD5"},
        {450.0f, "RockE1"},
        {350.0f, "RockE2"},
        {300.0f, "RockE3"},
        {525.0f, "RockF"},
        {450.0f, "RockG1"},
        {350.0f, "RockG2"},
        {460.0f, "RockG3"},
        {500.0f, "Dokan1"},
        {400.0f, "Dokan2"},
        {330.0f, "Dokan3"},
        {210.0f, "Dokan5"},
        {450.0f, "RKiller"},
        WM_EMPTY_CULL,
        WM_EMPTY_CULL,
        WM_EMPTY_CULL,
        WM_EMPTY_CULL,
    },

    { // WORLD 7
        WM_EMPTY_CULL,
        WM_EMPTY_CULL,
        WM_EMPTY_CULL,
        WM_EMPTY_CULL,
        WM_EMPTY_CULL,
        WM_EMPTY_CULL,
        WM_EMPTY_CULL,
        WM_EMPTY_CULL,
        WM_EMPTY_CULL,
        WM_EMPTY_CULL,
        WM_EMPTY_CULL,
        WM_EMPTY_CULL,
        WM_EMPTY_CULL,
        WM_EMPTY_CULL,
        WM_EMPTY_CULL,
        WM_EMPTY_CULL,
        WM_EMPTY_CULL,
        WM_EMPTY_CULL,
        WM_EMPTY_CULL,
        WM_EMPTY_CULL,
        WM_EMPTY_CULL,
        WM_EMPTY_CULL,
        WM_EMPTY_CULL,
        WM_EMPTY_CULL,
        WM_EMPTY_CULL,
        WM_EMPTY_CULL,
        WM_EMPTY_CULL,
        WM_EMPTY_CULL,
        WM_EMPTY_CULL,
        WM_EMPTY_CULL,
    },

    { // WORLD 8
        {300.0f, "blockA"},
        {350.0f, "blockB"},
        {350.0f, "blockC"},
        {450.0f, "blockD"},
        {300.0f, "blockE"},
        {300.0f, "blockF"},
        {300.0f, "blockG"},
        {250.0f, "blockH"},
        WM_EMPTY_CULL,
        WM_EMPTY_CULL,
        WM_EMPTY_CULL,
        WM_EMPTY_CULL,
        WM_EMPTY_CULL,
        WM_EMPTY_CULL,
        WM_EMPTY_CULL,
        WM_EMPTY_CULL,
        WM_EMPTY_CULL,
        WM_EMPTY_CULL,
        WM_EMPTY_CULL,
        WM_EMPTY_CULL,
        WM_EMPTY_CULL,
        WM_EMPTY_CULL,
        WM_EMPTY_CULL,
        WM_EMPTY_CULL,
        WM_EMPTY_CULL,
        WM_EMPTY_CULL,
        WM_EMPTY_CULL,
        WM_EMPTY_CULL,
        WM_EMPTY_CULL,
        WM_EMPTY_CULL,
    },

    { // WORLD 9
        WM_EMPTY_CULL,
        WM_EMPTY_CULL,
        WM_EMPTY_CULL,
        WM_EMPTY_CULL,
        WM_EMPTY_CULL,
        WM_EMPTY_CULL,
        WM_EMPTY_CULL,
        WM_EMPTY_CULL,
        WM_EMPTY_CULL,
        WM_EMPTY_CULL,
        WM_EMPTY_CULL,
        WM_EMPTY_CULL,
        WM_EMPTY_CULL,
        WM_EMPTY_CULL,
        WM_EMPTY_CULL,
        WM_EMPTY_CULL,
        WM_EMPTY_CULL,
        WM_EMPTY_CULL,
        WM_EMPTY_CULL,
        WM_EMPTY_CULL,
        WM_EMPTY_CULL,
        WM_EMPTY_CULL,
        WM_EMPTY_CULL,
        WM_EMPTY_CULL,
        WM_EMPTY_CULL,
        WM_EMPTY_CULL,
        WM_EMPTY_CULL,
        WM_EMPTY_CULL,
        WM_EMPTY_CULL,
        WM_EMPTY_CULL,
    }
};
